services:
  backend:
    container_name: otterly-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    expose:
      - ${SERVER_PORT}
    volumes:
      - ./:/app
    networks:
      - otterly-backend-network

networks:
  otterly-backend-network:
    driver: bridge

volumes:
  data:
    name: otterly-backend-data