// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health-check": {
            "get": {
                "description": "Check API health",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health Check"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.WrappedResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "routes.MemStats": {
            "type": "object",
            "properties": {
                "alloc": {
                    "type": "number"
                },
                "date": {
                    "type": "string"
                },
                "gc_cycle": {
                    "type": "integer"
                },
                "gc_last": {
                    "type": "integer"
                },
                "gc_next": {
                    "type": "integer"
                },
                "sys": {
                    "type": "number"
                }
            }
        },
        "routes.WrappedResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/routes.MemStats"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Otterly API",
	Description:      "Official Otterly API documentation.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
