basePath: /
definitions:
  github_com_otterly-id_otterly_backend_internal_api_models.CreateUserRequest:
    properties:
      email:
        maxLength: 254
        type: string
      full_name:
        maxLength: 100
        type: string
      name:
        maxLength: 50
        minLength: 2
        type: string
      password:
        maxLength: 255
        minLength: 8
        type: string
      phone_number:
        maxLength: 20
        type: string
      role:
        enum:
        - USER
        - OWNER
        type: string
    required:
    - email
    - name
    - password
    - role
    type: object
  github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse:
    properties:
      errors: {}
      message:
        type: string
      success:
        type: boolean
    type: object
  ? github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponse-array_github_com_otterly-id_otterly_backend_internal_api_models_UserResponse
  : properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  ? github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponse-github_com_otterly-id_otterly_backend_internal_api_models_CreateUserResponse
  : properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  ? github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponse-github_com_otterly-id_otterly_backend_internal_api_models_UpdateUserResponse
  : properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  ? github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponse-github_com_otterly-id_otterly_backend_internal_api_models_UserResponse
  : properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponseWithoutData:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  github_com_otterly-id_otterly_backend_internal_api_models.UpdateUserRequest:
    properties:
      email:
        maxLength: 254
        type: string
      full_name:
        maxLength: 100
        type: string
      name:
        maxLength: 50
        type: string
      phone_number:
        maxLength: 20
        type: string
    type: object
info:
  contact: {}
  description: Official Otterly API documentation.
  title: Otterly API
  version: "1.0"
paths:
  /api/users:
    get:
      consumes:
      - application/json
      description: Get all users data.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponse-array_github_com_otterly-id_otterly_backend_internal_api_models_UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
      summary: Get All Users
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: Add new user data.
      parameters:
      - description: Create user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponse-github_com_otterly-id_otterly_backend_internal_api_models_CreateUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
      summary: Create User
      tags:
      - Users
  /api/users/{id}:
    delete:
      consumes:
      - application/json
      description: Remove user data based on provided ID.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponseWithoutData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
      summary: Delete User
      tags:
      - Users
    get:
      consumes:
      - application/json
      description: Get user data based on provided ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponse-github_com_otterly-id_otterly_backend_internal_api_models_UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
      summary: Get User by ID
      tags:
      - Users
    patch:
      consumes:
      - application/json
      description: Edit user data based on provided ID.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Update user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponse-github_com_otterly-id_otterly_backend_internal_api_models_UpdateUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
      summary: Update User
      tags:
      - Users
swagger: "2.0"
