basePath: /
definitions:
  github_com_otterly-id_otterly_backend_internal_api_models.CreateUserRequest:
    properties:
      email:
        maxLength: 254
        type: string
      full_name:
        maxLength: 100
        type: string
      name:
        maxLength: 50
        minLength: 2
        type: string
      password:
        maxLength: 255
        minLength: 8
        type: string
      phone_number:
        maxLength: 20
        type: string
      role:
        enum:
        - USER
        - OWNER
        type: string
    required:
    - email
    - name
    - password
    - role
    type: object
  github_com_otterly-id_otterly_backend_internal_api_models.CreateUserResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: string
      name:
        type: string
      phone_number:
        type: string
      role:
        $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.UserRole'
    type: object
  github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse:
    properties:
      errors: {}
      message:
        type: string
      success:
        type: boolean
    type: object
  github_com_otterly-id_otterly_backend_internal_api_models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  github_com_otterly-id_otterly_backend_internal_api_models.RegisterRequest:
    properties:
      email:
        maxLength: 254
        type: string
      name:
        maxLength: 50
        minLength: 2
        type: string
      password:
        maxLength: 255
        type: string
    required:
    - email
    - name
    - password
    type: object
  github_com_otterly-id_otterly_backend_internal_api_models.RegisterResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  github_com_otterly-id_otterly_backend_internal_api_models.RoleResponse:
    properties:
      role:
        $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.UserRole'
    type: object
  ? github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponse-array_github_com_otterly-id_otterly_backend_internal_api_models_UserResponse
  : properties:
      data:
        items:
          $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.UserResponse'
        type: array
      message:
        type: string
      success:
        type: boolean
    type: object
  ? github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponse-github_com_otterly-id_otterly_backend_internal_api_models_CreateUserResponse
  : properties:
      data:
        $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.CreateUserResponse'
      message:
        type: string
      success:
        type: boolean
    type: object
  ? github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponse-github_com_otterly-id_otterly_backend_internal_api_models_RegisterResponse
  : properties:
      data:
        $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.RegisterResponse'
      message:
        type: string
      success:
        type: boolean
    type: object
  ? github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponse-github_com_otterly-id_otterly_backend_internal_api_models_RoleResponse
  : properties:
      data:
        $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.RoleResponse'
      message:
        type: string
      success:
        type: boolean
    type: object
  ? github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponse-github_com_otterly-id_otterly_backend_internal_api_models_UpdateUserResponse
  : properties:
      data:
        $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.UpdateUserResponse'
      message:
        type: string
      success:
        type: boolean
    type: object
  ? github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponse-github_com_otterly-id_otterly_backend_internal_api_models_UserResponse
  : properties:
      data:
        $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.UserResponse'
      message:
        type: string
      success:
        type: boolean
    type: object
  github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponseWithoutData:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  github_com_otterly-id_otterly_backend_internal_api_models.UpdateUserRequest:
    properties:
      email:
        maxLength: 254
        type: string
      full_name:
        maxLength: 100
        type: string
      name:
        maxLength: 50
        type: string
      phone_number:
        maxLength: 20
        type: string
    type: object
  github_com_otterly-id_otterly_backend_internal_api_models.UpdateUserResponse:
    properties:
      email:
        type: string
      full_name:
        type: string
      id:
        type: string
      name:
        type: string
      phone_number:
        type: string
      role:
        $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.UserRole'
      updated_at:
        type: string
    type: object
  github_com_otterly-id_otterly_backend_internal_api_models.UserResponse:
    properties:
      email:
        type: string
      full_name:
        type: string
      id:
        type: string
      name:
        type: string
      phone_number:
        type: string
      role:
        $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.UserRole'
    type: object
  github_com_otterly-id_otterly_backend_internal_api_models.UserRole:
    enum:
    - ADMIN
    - USER
    - OWNER
    type: string
    x-enum-varnames:
    - RoleAdmin
    - RoleUser
    - RoleOwner
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Official Otterly API documentation.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Otterly API
  version: "1.0"
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: Login using email and password.
      parameters:
      - description: Login request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponse-github_com_otterly-id_otterly_backend_internal_api_models_RoleResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
      summary: Login
      tags:
      - Auth
  /api/auth/logout:
    post:
      consumes:
      - application/json
      description: Logout the current authenticated user by removing the JWT cookie.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponseWithoutData'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
      security:
      - CookieAuth: []
      summary: Logout
      tags:
      - Auth
  /api/auth/me:
    get:
      consumes:
      - application/json
      description: Get current authenticated user data.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponse-github_com_otterly-id_otterly_backend_internal_api_models_UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
      security:
      - CookieAuth: []
      summary: Get Authenticated User
      tags:
      - Auth
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: Register new user.
      parameters:
      - description: Register request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponse-github_com_otterly-id_otterly_backend_internal_api_models_RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
      summary: Register
      tags:
      - Auth
  /api/users:
    get:
      consumes:
      - application/json
      description: Get all users data.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponse-array_github_com_otterly-id_otterly_backend_internal_api_models_UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
      security:
      - CookieAuth: []
      summary: Get All Users
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: Add new user data.
      parameters:
      - description: Create user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponse-github_com_otterly-id_otterly_backend_internal_api_models_CreateUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
      security:
      - CookieAuth: []
      summary: Create User
      tags:
      - Users
  /api/users/{id}:
    delete:
      consumes:
      - application/json
      description: Remove user data based on provided ID.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponseWithoutData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
      security:
      - CookieAuth: []
      summary: Delete User
      tags:
      - Users
    get:
      consumes:
      - application/json
      description: Get user data based on provided ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponse-github_com_otterly-id_otterly_backend_internal_api_models_UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
      security:
      - CookieAuth: []
      summary: Get User by ID
      tags:
      - Users
    patch:
      consumes:
      - application/json
      description: Edit user data based on provided ID.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Update user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.SuccessResponse-github_com_otterly-id_otterly_backend_internal_api_models_UpdateUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_otterly-id_otterly_backend_internal_api_models.FailureResponse'
      security:
      - CookieAuth: []
      summary: Update User
      tags:
      - Users
securityDefinitions:
  CookieAuth:
    description: JWT token stored in httpOnly cookie for authentication
    in: cookie
    name: otterly_token
    type: apiKey
swagger: "2.0"
tags:
- description: Authentication operations
  name: Auth
- description: User management operations
  name: Users
- description: Admin-only operations
  name: Admin
- description: Owner-only operations
  name: Owner
- description: Management operations (Admin or Owner)
  name: Management
